version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v
      - restore_cache:
          name: Restore cached dependencies
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache dependencies
          key: dependency-cache-{{ checksum "package-lock.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Test
            command: npm run test

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
