version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v
      - run:
          name: Install dependencies
          command: npm install
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build

  build:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Test
            command: npm run test
