version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Node version
          command: node -v
      - run:
          name: NPM version
          command: npm -v
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build

  test:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout
        - run:
            name: Test
            command: npm run test
